// Stories-Economy
using Content.Client.UserInterface.Controls;
using Content.Shared.IdentityManagement;
using Content.Shared.VendingMachines;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using System.Numerics;
using Robust.Client.Input;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.VendingMachines.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VendingMachineMenu : FancyWindow
    {
        [Dependency] private IPrototypeManager _prototypeManager = default!;
        [Dependency] private IEntityManager _entityManager = default!;

        private readonly Dictionary<EntProtoId, EntityUid> _dummies = new();
        
        public List<VendingMachineInventoryEntry> Inventory = new();

        public event Action<GUIBoundKeyEventArgs, ListData>? OnItemSelected;

        public VendingMachineMenu()
        {
            MinSize = SetSize = new Vector2(350, 450);
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            VendingContents.SearchBar = SearchBar;
            VendingContents.DataFilterCondition += DataFilterCondition;
            VendingContents.GenerateItem += GenerateButton;
            VendingContents.ItemKeyBindDown += (args, data) => OnItemSelected?.Invoke(args, data);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            // Don't clean up dummies during disposal or we'll just have to spawn them again
            if (!disposing)
                return;

            // Delete any dummy items we spawned
            foreach (var entity in _dummies.Values)
            {
                _entityManager.QueueDeleteEntity(entity);
            }
            _dummies.Clear();
        }

        private bool DataFilterCondition(string filter, ListData data)
        {
            if (data is not VendorItemsListData { ItemText: var text })
                return false;

            if (string.IsNullOrEmpty(filter))
                return true;

            return text.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
        }

        private void GenerateButton(ListData data, ListContainerButton button)
        {
            if (data is not VendorItemsListData { ItemProtoID: var protoID, ItemText: var text, Price: var price, Amount: var amount })
                return;

            var item = new VendingMachineItem(protoID, text);
            button.AddChild(item);
            button.AddStyleClass("ButtonSquare");

            bool isOutOfStock = amount == 0;

            button.Disabled = isOutOfStock;

            if (isOutOfStock)
            {
                 item.Modulate = Color.Gray;
            }
        }

        /// <summary>
        /// Populates the list of available items on the vending machine interface
        /// and sets icons based on their prototypes
        /// </summary>
        public void Populate(List<VendingMachineInventoryEntry> inventory)
        {
            Inventory = inventory;
            VendingContents.PopulateList(new List<ListData>()); 

            if (inventory.Count == 0)
            {
                return;
            }

            var listData = new List<ListData>();

            for (var i = 0; i < inventory.Count; i++)
            {
                var entry = inventory[i];

                if (!_prototypeManager.TryIndex(entry.ID, out var prototype))
                    continue;

                if (!_dummies.TryGetValue(entry.ID, out var dummy))
                {
                    dummy = _entityManager.Spawn(entry.ID);
                    _dummies.Add(entry.ID, dummy);
                }

                var itemName = Identity.Name(dummy, _entityManager);
                string itemText;

                if (entry.Price > 0)
                {
                    itemText = Loc.GetString("vending-machine-item-entry-with-price", 
                        ("name", itemName), 
                        ("amount", entry.Amount), 
                        ("price", entry.Price));
                }
                else
                {
                    itemText = Loc.GetString("vending-machine-item-entry-no-price", 
                        ("name", itemName), 
                        ("amount", entry.Amount));
                }

                listData.Add(new VendorItemsListData(prototype.ID, i)
                {
                    ItemText = itemText,
                    Price = entry.Price,
                    Amount = entry.Amount
                });
            }

            VendingContents.PopulateList(listData);
        }

        public void UpdateBalance(int? balance)
        {
            if (balance.HasValue)
            {
                BalanceLabel.Text = Loc.GetString("vending-machine-ui-balance", ("balance", balance.Value));
            }
            else
            {
                BalanceLabel.Text = Loc.GetString("vending-machine-ui-balance", ("balance", Loc.GetString("vending-machine-ui-no-balance")));
            }
        }
    }

    public record VendorItemsListData(EntProtoId ItemProtoID, int ItemIndex) : ListData
    {
        public string ItemText = string.Empty;
        public uint Price;
        public uint Amount;
    }
}
