- type: job
  id: STRepresentativeCentcom
  name: stories-job-name-representative-centcom
  description: stories-job-description-representative-centcom
  playTimeTracker: JobSTRepresentativeCentcom
  setPreference: false
  startingGear: STRepresentativeCentcomGear
  icon: "JobIconSTCentcom"
  supervisors: stories-job-supervisors-chief-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  - PrisonAllAccess # Stories
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm, RadioImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: NanotrasenStaff

- type: startingGear
  id: STRepresentativeCentcomGear
  equipment:
    head: ClothingHeadHatCentcomcap
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    back: ClothingBackpackSatchelLeather
    eyes: STClothingEyesGlassesCentcom
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsLaceup
    id: STRepresentativeCentcomPDA
    outerClothing: ClothingOuterArmorCentcommCarapace
    neck: ClothingNeckCloakCentcom
    belt: BoxFolderCentComClipboard
  storage:
    back:
    - BoxSurvival
