using System.Text.RegularExpressions;
using Content.Shared._Stories.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Economy;

[GenerateTypedNameReferences]
public sealed partial class BankCartridgeUiFragment : BoxContainer
{
    public BankCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);

        TransferButton.OnPressed += _ =>
        {
            if (int.TryParse(AmountInput.Text, out var amount))
                OnTransfer?.Invoke(TargetInput.Text, amount);
        };

        LinkButton.OnPressed += _ => OnLink?.Invoke();
        UnlinkButton.OnPressed += _ => OnUnlink?.Invoke();
        ToggleNotificationsButton.OnPressed += _ => OnToggleNotifications?.Invoke();

        var numberRegex = new Regex("^[0-9]*$");
        AmountInput.OnTextChanged += args =>
        {
            if (!numberRegex.IsMatch(args.Text))
                args.Control.Text = numberRegex.Replace(args.Text, "");
        };
        TargetInput.OnTextChanged += args =>
        {
            if (!numberRegex.IsMatch(args.Text))
                args.Control.Text = numberRegex.Replace(args.Text, "");
        };
    }

    public event Action<string, int>? OnTransfer;
    public event Action? OnLink;
    public event Action? OnUnlink;
    public event Action? OnToggleNotifications;

    public void UpdateState(BankCartridgeUiState state)
    {
        OwnerName.Text = state.OwnerName;
        Balance.Text = $"{state.Balance} кр.";
        AccountNumber.Text = state.AccountNumber;

        var cardInserted = state.OwnerName != Loc.GetString("stories-bank-ui-insert-id");

        LinkButton.Disabled = !cardInserted || state.IsIdLinked;
        UnlinkButton.Disabled = !state.IsIdLinked;
        TransferButton.Disabled = !state.IsIdLinked;
        AmountInput.Editable = state.IsIdLinked;
        TargetInput.Editable = state.IsIdLinked;

        ToggleNotificationsButton.Text = state.NotificationsEnabled
            ? Loc.GetString("stories-bank-ui-notifications-disable")
            : Loc.GetString("stories-bank-ui-notifications-enable");
    }
}
