- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleEmpireMember
  name: EmpireMember Role
  components:
  - type: MindRole
    antagPrototype: EmpireMember
    exclusiveAntag: true
    roleType: TeamAntagonist
  - type: EmpireMemberRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHypnotizedEmpireMember
  name: HypnotizedEmpireMember Role
  components:
  - type: MindRole
    antagPrototype: HypnotizedEmpireMember
    exclusiveAntag: true
    roleType: TeamAntagonist
  - type: HypnotizedEmpireMemberRole

- type: entity
  parent: BaseMindRoleAntag
  id: STMindRoleShadowling
  name: Shadowling role
  components:
  - type: MindRole
    antagPrototype: STShadowling
    exclusiveAntag: true
    roleType: TeamAntagonist
  - type: ShadowlingRole

- type: entity
  parent: BaseMindRoleAntag
  id: STMindRoleShadowlingThrall
  name: Shadowling thrall role
  components:
  - type: MindRole
    antagPrototype: STShadowlingThrall
    exclusiveAntag: true
    roleType: TeamAntagonist
  - type: ShadowlingThrallRole

- type: entity
  parent: BaseMindRoleAntag
  id: STMindRolePontific
  name: Pontific Role
  components:
  - type: MindRole
    antagPrototype: STPontific
    roleType: TeamAntagonist
    subtype: stories-role-subtype-pontific
