# Космическая Тюрьма
- type: antagSpecifier
  abstract: true
  parent: BaseAntagSpecifier
  id: STSpacePrisonBlacklistedAntag
  jobBlacklist:
  - PRISONHeadOfPrison
  - PRISONEngineer
  - PRISONMedic
  - PRISONOfficer
  - PRISONPrisoner
