- type: antag
  id: STShadowling
  name: stories-roles-antag-shadowling-name
  antagonist: true
  setPreference: true
  objective: stories-roles-antag-shadowling-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000

- type: antag
  id: STShadowlingThrall
  name: stories-roles-antag-shadowling-thrall-name
  antagonist: true
  setPreference: false
  objective: stories-roles-antag-shadowling-thrall-objective
