# Prison-Jobs

- type: playTimeTracker
  id: JobPrisoner

- type: playTimeTracker
  id: JobHeadOfSpacePrison

- type: playTimeTracker
  id: JobSpacePrisonOfficer

- type: playTimeTracker
  id: JobSpacePrisonEngineer

- type: playTimeTracker
  id: JobSpacePrisonMedic

# Event-Restricted-Jobs

- type: playTimeTracker
  id: JobSTSecurityClown

- type: playTimeTracker
  id: JobSTCommandMaid

- type: playTimeTracker
  id: JobSTPartyMaker

# Centcom-Jobs

- type: playTimeTracker
  id: JobSTChiefCentcom

- type: playTimeTracker
  id: JobSTOperatorCentcom

- type: playTimeTracker
  id: JobSTRepresentativeCentcom

- type: playTimeTracker
  id: JobSTHeadOfSecurityCentcom

- type: playTimeTracker
  id: JobGuardianNt

- type: playTimeTracker
  id: JobSTSecurityOfficerCentcom

- type: playTimeTracker
  id: JobSTMedicCentcom

- type: playTimeTracker
  id: JobSTEngineerCentcom

- type: playTimeTracker
  id: JobSTWorkerCentcom

# Juridical-Jobs

- type: playTimeTracker
  id: JobSTMagistrate

- type: playTimeTracker
  id: JobIAA

- type: playTimeTracker
  id: STJobJudge

# DSO-Jobs

- type: playTimeTracker
  id: STJobSpecialOfficer

# Other-Jobs

- type: playTimeTracker
  id: STJobBrigmedic