- type: department
  id: Prison
  name: department-Prison
  description: department-Cargo-description
  color: "#e99844"
  roles:
  - PRISONHeadOfPrison
  - PRISONEngineer
  - PRISONMedic
  - PRISONOfficer
  - PRISONPrisoner

- type: department
  id: STJuridical
  name: stories-department-Juridical
  description: stories-department-Juridical-description
  color: "#6d5d53"
  roles:
  - STMagistrate
  - IAA
  - Lawyer
  - STJudge

- type: department
  id: STDSO
  name: stories-department-DSO
  description: stories-department-DSO-description
  color: "#0a5fad"
  roles:
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  editorHidden: true
  weight: 130

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0f8551"
  roles:
  - STChiefCentcom
  - STOperatorCentcom
  - STRepresentativeCentcom
  - STHeadOfSecurityCentcom
  - STSecurityOfficerCentcom
  - STMedicCentcom
  - STEngineerCentcom
  - STWorkerCentcom
  editorHidden: true
  weight: 120
