using System.Text.RegularExpressions;
using Content.Client.UserInterface.Controls;
using Content.Shared._Stories.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class AtmWindow : FancyWindow
{
    private readonly AtmBoundUserInterface _bui;
    private string _prefillAccountNumber = string.Empty;
    private string _prefillPin = string.Empty;

    public AtmWindow(AtmBoundUserInterface bui)
    {
        RobustXamlLoader.Load(this);
        _bui = bui;

        LoginButton.OnPressed += _ => _bui.Login(AccountNumberInput.Text, PinInput.Text);
        LogoutButton.OnPressed += _ => _bui.Logout();

        FillFromCardButton.OnPressed += _ =>
        {
            if (!string.IsNullOrEmpty(_prefillAccountNumber))
            {
                AccountNumberInput.Text = _prefillAccountNumber;
                PinInput.Text = _prefillPin;
            }
        };

        Withdraw10Button.Text = Loc.GetString("stories-atm-ui-withdraw-option", ("amount", 10));
        Withdraw50Button.Text = Loc.GetString("stories-atm-ui-withdraw-option", ("amount", 50));
        Withdraw100Button.Text = Loc.GetString("stories-atm-ui-withdraw-option", ("amount", 100));
        Withdraw500Button.Text = Loc.GetString("stories-atm-ui-withdraw-option", ("amount", 500));

        Withdraw10Button.OnPressed += _ => _bui.Withdraw(10);
        Withdraw50Button.OnPressed += _ => _bui.Withdraw(50);
        Withdraw100Button.OnPressed += _ => _bui.Withdraw(100);
        Withdraw500Button.OnPressed += _ => _bui.Withdraw(500);
        CustomWithdrawButton.OnPressed += _ =>
        {
            if (int.TryParse(CustomWithdrawAmount.Text, out var amount) && amount > 0)
                _bui.Withdraw(amount);
        };

        var numberRegex = new Regex("^[0-9]*$");
        AccountNumberInput.OnTextChanged += args => ValidateInput(args, numberRegex, 8);
        PinInput.OnTextChanged += args => ValidateInput(args, numberRegex, 4);
        CustomWithdrawAmount.OnTextChanged += args => ValidateInput(args, numberRegex, 9);
    }

    private void ValidateInput(LineEdit.LineEditEventArgs args, Regex regex, int maxLength)
    {
        var changed = false;
        var text = args.Text;

        if (!regex.IsMatch(text))
        {
            text = regex.Replace(text, "");
            changed = true;
        }

        if (text.Length > maxLength)
        {
            text = text.Substring(0, maxLength);
            changed = true;
        }

        if (changed)
        {
            args.Control.Text = text;
            args.Control.CursorPosition = text.Length;
        }
    }

    public void UpdateState(AtmBoundUserInterfaceState state)
    {
        LoginView.Visible = !state.IsLoggedIn;
        MainView.Visible = state.IsLoggedIn;

        if (!string.IsNullOrEmpty(state.PrefillAccountNumber))
        {
            _prefillAccountNumber = state.PrefillAccountNumber;
            _prefillPin = state.PrefillPin;
        }

        FillFromCardButton.Visible = !string.IsNullOrEmpty(_prefillAccountNumber);

        if (state.IsLoggedIn)
        {
            WelcomeLabel.Text = Loc.GetString("stories-atm-ui-welcome-user", ("user", state.OwnerName));
            BalanceLabel.Text = Loc.GetString("stories-atm-ui-balance-value", ("balance", state.Balance));
            CustomWithdrawAmount.Clear();
        }
        else
        {
            AccountNumberInput.Clear();
            PinInput.Clear();
        }

        StatusMessage.Text = state.Message;

        if (!string.IsNullOrEmpty(state.Message))
            StatusMessage.FontColorOverride = Color.Yellow;
        else
            StatusMessage.FontColorOverride = Color.White;
    }
}
