using Content.Client.UserInterface.Controls;
using Content.Shared._Stories.Economy;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using System.Globalization;
using Robust.Shared.Utility;

namespace Content.Client._Stories.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class BankCentcomConsoleWindow : FancyWindow
{
    private List<AccountDto> _accounts = new();
    private List<StationDto> _stations = new();
    private List<FinancialLogDto> _logs = new();
    private NetEntity? _selectedStation;

    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public Action? OnRefresh;
    public Action<NetEntity>? OnChangeStation;
    public Action<NetEntity, CentcomFineTarget, string, int, string, bool, bool, bool, string?>? OnIssueFine;
    public Action<NetEntity, float, float>? OnSetSalary;
    public Action<NetEntity, string, int, bool, bool>? OnEditAccount;
    public Action<NetEntity, string, int>? OnCreateAccount;
    public Action<NetEntity, string>? OnResetPin;

    public BankCentcomConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Tabs.SetTabTitle(0, Loc.GetString("stories-bank-centcom-tab-operations"));
        Tabs.SetTabTitle(1, Loc.GetString("stories-bank-centcom-tab-accounts"));
        Tabs.SetTabTitle(2, Loc.GetString("stories-bank-security-tab-logs"));

        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
        LogSearchBar.OnTextChanged += _ => UpdateLogs();
        AccSearchBar.OnTextChanged += _ => UpdateAccInfoList();

        StationSelector.OnItemSelected += args =>
        {
            StationSelector.SelectId(args.Id);
            if (args.Id >= 0 && args.Id < _stations.Count)
                OnChangeStation?.Invoke(_stations[args.Id].NetId);
        };

        FineTypeSelector.AddItem(Loc.GetString("stories-bank-centcom-target-crew"), (int)CentcomFineTarget.Crew);
        FineTypeSelector.AddItem(Loc.GetString("stories-bank-centcom-target-dept"), (int)CentcomFineTarget.Department);
        FineTypeSelector.AddItem(Loc.GetString("stories-bank-centcom-target-allcrew"), (int)CentcomFineTarget.AllCrew);
        FineTypeSelector.AddItem(Loc.GetString("stories-bank-centcom-target-alldepts"), (int)CentcomFineTarget.AllDepartments);
        FineTypeSelector.AddItem(Loc.GetString("stories-bank-centcom-target-all"), (int)CentcomFineTarget.All);

        FineTypeSelector.OnItemSelected += args =>
        {
            FineTypeSelector.SelectId(args.Id);
            UpdateFineTargetSelector((CentcomFineTarget)args.Id);
        };

        FineTargetSelector.OnItemSelected += args =>
        {
            FineTargetSelector.SelectId(args.Id);
        };

        FineAmountSpinBox.Value = 100;
        FineAmountSpinBox.IsValid = n => n > 0;
        SalaryFrequencySpinBox.Value = 30;
        SalaryFrequencySpinBox.IsValid = n => n > 0;
        EditBalanceSpinBox.IsValid = n => n >= 0;
        CreateAccBalanceSpinBox.Value = 100;
        CreateAccBalanceSpinBox.IsValid = n => n >= 0;

        FineAnnounceCheckBox.OnToggled += args =>
        {
            AnnouncementContainer.Visible = args.Pressed;

            var currentText = Rope.Collapse(AnnouncementTextEdit.TextRope);
            if (args.Pressed && string.IsNullOrWhiteSpace(currentText))
            {
                AnnouncementTextEdit.TextRope = new Rope.Leaf(Loc.GetString("stories-bank-centcom-announcement-fine-default"));
            }
        };

        CreateAccButton.OnPressed += _ =>
        {
            if (_selectedStation == null) return;
            var name = CreateAccNameInput.Text;
            var bal = CreateAccBalanceSpinBox.Value;
            if (!string.IsNullOrWhiteSpace(name))
            {
                OnCreateAccount?.Invoke(_selectedStation.Value, name, bal);
                CreateAccNameInput.Clear();
            }
        };

        IssueFineButton.OnPressed += _ =>
        {
            if (_selectedStation == null) return;
            var targetType = (CentcomFineTarget)FineTypeSelector.SelectedId;
            var targetId = "";

            if (targetType == CentcomFineTarget.Crew || targetType == CentcomFineTarget.Department)
            {
                if (FineTargetSelector.ItemCount == 0) return;
                targetId = (string)GetSelectedMetadata(FineTargetSelector)!;
            }

            var amount = FineAmountSpinBox.Value;
            var reason = FineReasonLineEdit.Text;
            var isPercentage = FineIsPercentageCheckBox.Pressed;
            var notify = FineSendNotificationCheckBox.Pressed;
            var announce = FineAnnounceCheckBox.Pressed;

            string? announcementText = announce ? Rope.Collapse(AnnouncementTextEdit.TextRope) : null;

            if (amount > 0 && !string.IsNullOrWhiteSpace(reason))
            {
                OnIssueFine?.Invoke(_selectedStation.Value, targetType, targetId, amount, reason, isPercentage, notify, announce, announcementText);
                FineReasonLineEdit.Clear();
            }
        };

        ApplySalaryButton.OnPressed += _ =>
        {
            if (_selectedStation == null) return;
            if (float.TryParse(SalaryModifierInput.Text, NumberStyles.Any, CultureInfo.InvariantCulture, out var mod))
            {
                OnSetSalary?.Invoke(_selectedStation.Value, mod, SalaryFrequencySpinBox.Value);
            }
        };

        AccountItemList.OnItemSelected += args =>
        {
            if (args.ItemList.GetSelected().First().Metadata is AccountDto acc)
            {
                InfoOwnerLabel.Text = acc.DisplayName;
                InfoNumberLabel.Text = acc.Id;
                InfoBalanceLabel.Text = $"{acc.Balance} кр.";
                ResetPinButton.Disabled = acc.IsDepartment;
            }
        };

        EditBalanceButton.OnPressed += _ =>
        {
            if (_selectedStation == null || !AccountItemList.GetSelected().Any()) return;
            var selectedItem = AccountItemList.GetSelected().First();
            if (selectedItem.Metadata is not AccountDto acc) return;

            OnEditAccount?.Invoke(_selectedStation.Value, acc.Id, EditBalanceSpinBox.Value, false, acc.IsDepartment);
        };

        DeleteAccountButton.OnPressed += _ =>
        {
            if (_selectedStation == null || !AccountItemList.GetSelected().Any()) return;
            var selectedItem = AccountItemList.GetSelected().First();
            if (selectedItem.Metadata is not AccountDto acc) return;

            OnEditAccount?.Invoke(_selectedStation.Value, acc.Id, 0, true, acc.IsDepartment);
        };

        ResetPinButton.OnPressed += _ =>
        {
            if (_selectedStation == null || !AccountItemList.GetSelected().Any()) return;
            var selectedItem = AccountItemList.GetSelected().First();
            if (selectedItem.Metadata is not AccountDto acc || acc.IsDepartment) return;

            OnResetPin?.Invoke(_selectedStation.Value, acc.Id);
        };
    }

    private string LocalizeAccountName(string id)
    {
        if (_prototypeManager.TryIndex<CargoAccountPrototype>(id, out var cargoAcc))
            return Loc.GetString(cargoAcc.Name);
        return id;
    }

    private void UpdateFineTargetSelector(CentcomFineTarget targetType)
    {
        var previousSelection = GetSelectedMetadata(FineTargetSelector) as string;

        FineTargetSelector.Clear();
        FineTargetSelector.Disabled = targetType == CentcomFineTarget.AllCrew || targetType == CentcomFineTarget.AllDepartments || targetType == CentcomFineTarget.All;

        int i = 0;
        int selectIndex = 0;
        if (targetType == CentcomFineTarget.Crew)
        {
            foreach (var acc in _accounts.Where(a => !a.IsDepartment))
            {
                string display = $"{acc.DisplayName} ({acc.Id})";
                FineTargetSelector.AddItem(display, i);
                FineTargetSelector.SetItemMetadata(i, acc.Id);
                if (acc.Id == previousSelection)
                    selectIndex = i;
                i++;
            }
        }
        else if (targetType == CentcomFineTarget.Department)
        {
            foreach (var acc in _accounts.Where(a => a.IsDepartment))
            {
                FineTargetSelector.AddItem(LocalizeAccountName(acc.Id), i);
                FineTargetSelector.SetItemMetadata(i, acc.Id);
                if (acc.Id == previousSelection)
                    selectIndex = i;
                i++;
            }
        }

        if (FineTargetSelector.ItemCount > 0)
            FineTargetSelector.SelectId(selectIndex);
    }

    private void UpdateAccInfoList()
    {
        AccountItemList.Clear();
        var filter = AccSearchBar.Text.ToLowerInvariant();

        foreach (var account in _accounts)
        {
            string display = account.IsDepartment ? LocalizeAccountName(account.Id) : $"{account.DisplayName} ({account.Id})";

            if (string.IsNullOrEmpty(filter) || display.ToLowerInvariant().Contains(filter))
            {
                var item = AccountItemList.AddItem(display);
                item.Metadata = account;
            }
        }
    }

    private void UpdateLogs()
    {
        LogsGrid.RemoveAllChildren();

        LogsGrid.AddChild(new Label { Text = Loc.GetString("stories-bank-security-time"), StyleClasses = { "LabelHeading" }, MinWidth = 70 });
        LogsGrid.AddChild(new Label { Text = Loc.GetString("stories-bank-security-source"), StyleClasses = { "LabelHeading" }, HorizontalExpand = true, SizeFlagsStretchRatio = 1 });
        LogsGrid.AddChild(new Label { Text = Loc.GetString("stories-bank-security-dest"), StyleClasses = { "LabelHeading" }, HorizontalExpand = true, SizeFlagsStretchRatio = 1 });
        LogsGrid.AddChild(new Label { Text = Loc.GetString("stories-bank-security-amount"), StyleClasses = { "LabelHeading" }, MinWidth = 60 });
        LogsGrid.AddChild(new Label { Text = Loc.GetString("stories-bank-security-reason"), StyleClasses = { "LabelHeading" }, HorizontalExpand = true, SizeFlagsStretchRatio = 3 });

        var filter = LogSearchBar.Text.ToLowerInvariant();

        foreach (var log in Enumerable.Reverse(_logs))
        {
            var src = LocalizeAccountName(log.Source);
            var dst = LocalizeAccountName(log.Destination);

            if (!string.IsNullOrEmpty(filter) &&
                !src.ToLowerInvariant().Contains(filter) &&
                !dst.ToLowerInvariant().Contains(filter) &&
                !log.Reason.ToLowerInvariant().Contains(filter))
            {
                continue;
            }

            LogsGrid.AddChild(new Label { Text = log.Timestamp.ToString(@"hh\:mm\:ss"), MinWidth = 70 });
            LogsGrid.AddChild(new Label { Text = src, HorizontalExpand = true, SizeFlagsStretchRatio = 1, StyleClasses = { "Monospace" }, ClipText = true });
            LogsGrid.AddChild(new Label { Text = dst, HorizontalExpand = true, SizeFlagsStretchRatio = 1, StyleClasses = { "Monospace" }, ClipText = true });
            LogsGrid.AddChild(new Label { Text = log.Amount.ToString(), FontColorOverride = Color.Gold, MinWidth = 60 });
            LogsGrid.AddChild(new Label { Text = log.Reason, HorizontalExpand = true, SizeFlagsStretchRatio = 3, ClipText = true, ToolTip = log.Reason });
        }
    }

    public void UpdateState(BankCentcomConsoleState state)
    {
        _stations = state.Stations;
        StationSelector.Clear();
        for (int i = 0; i < _stations.Count; i++)
        {
            StationSelector.AddItem(_stations[i].Name, i);
            if (state.SelectedStation == _stations[i].NetId)
                StationSelector.SelectId(i);
        }

        _selectedStation = state.SelectedStation;
        _accounts = state.Accounts;
        _logs = state.Logs;

        UpdateAccInfoList();
        UpdateFineTargetSelector((CentcomFineTarget)FineTypeSelector.SelectedId);
        UpdateLogs();

        SalaryModifierInput.Text = state.SalaryModifier.ToString(CultureInfo.InvariantCulture);
        SalaryFrequencySpinBox.Value = (int)state.SalaryFrequency;

        InfoOwnerLabel.Text = "---";
        InfoNumberLabel.Text = "---";
        InfoBalanceLabel.Text = "---";
        ResetPinButton.Disabled = true;
    }

    private object? GetSelectedMetadata(OptionButton button)
    {
        for (int idx = 0; idx < button.ItemCount; idx++)
        {
            if (button.GetItemId(idx) == button.SelectedId)
            {
                return button.GetItemMetadata(idx);
            }
        }
        return null;
    }
}
