using Content.Client.UserInterface.Controls;
using Content.Shared._Stories.Economy;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client._Stories.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class BankSecurityConsoleWindow : FancyWindow
{
    private List<AccountDto> _accounts = new();
    private List<FinancialLogDto> _logs = new();

    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public Action? OnRefresh;
    public Action<string, int, string>? OnIssueFine;

    public BankSecurityConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Tabs.SetTabTitle(0, Loc.GetString("stories-bank-security-tab-fines"));
        Tabs.SetTabTitle(1, Loc.GetString("stories-bank-security-tab-acc-info"));
        Tabs.SetTabTitle(2, Loc.GetString("stories-bank-security-tab-logs"));

        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
        LogSearchBar.OnTextChanged += _ => UpdateLogs();
        TargetSearchBar.OnTextChanged += _ => UpdateTargetList();
        AccSearchBar.OnTextChanged += _ => UpdateAccInfoList();

        AmountSpinBox.Value = 100;
        AmountSpinBox.IsValid = n => n > 0;

        IssueFineButton.OnPressed += _ =>
        {
            if (!TargetItemList.GetSelected().Any()) return;
            var selectedItem = TargetItemList.GetSelected().First();
            if (selectedItem.Metadata is not AccountDto targetAcc) return;

            var amount = AmountSpinBox.Value;
            var reason = ReasonLineEdit.Text;
            if (amount > 0 && !string.IsNullOrWhiteSpace(reason))
            {
                OnIssueFine?.Invoke(targetAcc.Id, amount, reason);
                ReasonLineEdit.Clear();
            }
        };

        AccItemList.OnItemSelected += args =>
        {
            if (args.ItemList.GetSelected().First().Metadata is AccountDto acc)
            {
                InfoOwnerLabel.Text = acc.DisplayName;
                InfoNumberLabel.Text = acc.Id;
                InfoBalanceLabel.Text = $"{acc.Balance} кр.";
            }
        };
    }

    private string LocalizeAccountName(string id)
    {
        if (_prototypeManager.TryIndex<CargoAccountPrototype>(id, out var cargoAcc))
            return Loc.GetString(cargoAcc.Name);
        return id;
    }

    private void UpdateTargetList()
    {
        TargetItemList.Clear();
        var filter = TargetSearchBar.Text.ToLowerInvariant();

        foreach (var account in _accounts)
        {
            if (account.IsDepartment) continue;

            string display = $"{account.DisplayName} ({account.Id})";
            if (string.IsNullOrEmpty(filter) || display.ToLowerInvariant().Contains(filter))
            {
                var item = TargetItemList.AddItem(display);
                item.Metadata = account;
            }
        }
    }

    private void UpdateAccInfoList()
    {
        AccItemList.Clear();
        var filter = AccSearchBar.Text.ToLowerInvariant();

        foreach (var account in _accounts)
        {
            string display = account.IsDepartment ? LocalizeAccountName(account.Id) : $"{account.DisplayName} ({account.Id})";

            if (string.IsNullOrEmpty(filter) || display.ToLowerInvariant().Contains(filter))
            {
                var item = AccItemList.AddItem(display);
                item.Metadata = account;
            }
        }
    }

    private void UpdateLogs()
    {
        LogsGrid.RemoveAllChildren();

        LogsGrid.AddChild(new Label { Text = Loc.GetString("stories-bank-security-time"), StyleClasses = { "LabelHeading" }, MinWidth = 70 });
        LogsGrid.AddChild(new Label { Text = Loc.GetString("stories-bank-security-source"), StyleClasses = { "LabelHeading" }, HorizontalExpand = true, SizeFlagsStretchRatio = 1 });
        LogsGrid.AddChild(new Label { Text = Loc.GetString("stories-bank-security-dest"), StyleClasses = { "LabelHeading" }, HorizontalExpand = true, SizeFlagsStretchRatio = 1 });
        LogsGrid.AddChild(new Label { Text = Loc.GetString("stories-bank-security-amount"), StyleClasses = { "LabelHeading" }, MinWidth = 60 });
        LogsGrid.AddChild(new Label { Text = Loc.GetString("stories-bank-security-reason"), StyleClasses = { "LabelHeading" }, HorizontalExpand = true, SizeFlagsStretchRatio = 3 });

        var filter = LogSearchBar.Text.ToLowerInvariant();

        foreach (var log in Enumerable.Reverse(_logs))
        {
            var src = LocalizeAccountName(log.Source);
            var dst = LocalizeAccountName(log.Destination);

            if (!string.IsNullOrEmpty(filter) &&
                !src.ToLowerInvariant().Contains(filter) &&
                !dst.ToLowerInvariant().Contains(filter) &&
                !log.Reason.ToLowerInvariant().Contains(filter))
            {
                continue;
            }

            LogsGrid.AddChild(new Label { Text = log.Timestamp.ToString(@"hh\:mm\:ss"), MinWidth = 70 });
            LogsGrid.AddChild(new Label { Text = src, HorizontalExpand = true, SizeFlagsStretchRatio = 1, StyleClasses = { "Monospace" }, ClipText = true });
            LogsGrid.AddChild(new Label { Text = dst, HorizontalExpand = true, SizeFlagsStretchRatio = 1, StyleClasses = { "Monospace" }, ClipText = true });
            LogsGrid.AddChild(new Label { Text = log.Amount.ToString(), FontColorOverride = Color.Gold, MinWidth = 60 });
            LogsGrid.AddChild(new Label { Text = log.Reason, HorizontalExpand = true, SizeFlagsStretchRatio = 3, ClipText = true, ToolTip = log.Reason });
        }
    }

    public void UpdateState(BankSecurityConsoleState state)
    {
        _logs = state.Logs;
        _accounts = state.KnownAccounts;

        UpdateTargetList();
        UpdateAccInfoList();
        UpdateLogs();

        InfoOwnerLabel.Text = "---";
        InfoNumberLabel.Text = "---";
        InfoBalanceLabel.Text = "---";
    }
}
