- type: entity
  id: CrateServicePrinter
  parent: CrateGenericSteel
  name: printer box
  description: A printer for all sorts of bureaucratic things.
  components:
  - type: StorageFill
    contents:
    - id: BoxPrinter
